### ISSUE TITLE
ログをテキストに出力したい

### ISSUE THREAD

**Issue by rokamu623** [azu-lab/PaperErrorChecker#12]
エラーログをコンソールでなくテキストに吐き出すような機構を追加してほしい。

現状、パイプでテキストに吐き出すと、`[ERROR] Insert a period`などだけコンソールに吐き出され、具体的な指摘点はテキストに吐き出されるという状況になっている。

**Comment by atsushi421** [comment]
@rokamu623 
パイプでファイルに出力した場合も、結果がそのまま書き出されるように修正しました。
時間あるときに確認してみて
